// Altyapının kendi metinleri (Türkçe + İngilizce). Oyuna özel metinler her oyunun config.js dosyasındadır.
export const KIT_TEXT = {
  tr: {
    level: 'Seviye {n}',
    daily: 'Günlük',
    next: 'Sonraki seviye',
    retry: 'Tekrar',
    double: '2 kat altın',
    added: 'Eklendi',
    coinsGained: '+{n} altın',
    tries: '{n}. denemede',
    backToLevels: 'Seviyelere dön',
    copyResult: 'Sonucu paylaş',
    copied: 'Kopyalandı',
    copyFail: 'Kopyalanamadı; metni seçip kopyala',
    shared: 'Paylaşıldı',
    close: 'Kapat',
    start: 'Başla',
    equipped: 'Takılı',
    equip: 'Tak',
    needCoins: '{n} altın daha lazım',
    buy: 'Satın al',
    restore: 'Satın alımları geri yükle',
    restored: 'Satın alımlar geri yüklendi',
    purchaseFailed: 'Satın alma tamamlanmadı',
    purchased: 'Satın alındı!',
    adTitle: 'Reklam',
    adBody: 'Prototip simülasyonu. Mağaza sürümünde burada gerçek bir ödüllü reklam oynar.',
    adFailed: 'Reklam şu an yüklenemedi, biraz sonra tekrar dene',
    interSim: 'Mağaza sürümünde burada bir geçiş reklamı olur',
    simTitle: 'Test satın alması',
    simBody: 'Bu bir prototip, gerçek ödeme alınmaz. Mağaza sürümünde burada App Store veya Google Play ödeme ekranı açılır.',
    simBuy: 'Satın almayı simüle et',
    simRestore: 'Geri yükleme mağaza sürümünde çalışır',
    cancel: 'Vazgeç',

    today: 'Bugün',
    road: 'Altın Yol',
    shop: 'Mağaza',
    settings: 'Ayarlar',

    dailyTitle: 'Günün Seviyesi',
    dailyNew: 'Herkes bugün aynı seviyeyle oynuyor. Çöz, 50 altın kazan ve serini koru.',
    dailyStreak: 'Seri: {n} gün.',
    dailyDone: 'Bugünü {n}. denemede çözdün. Seri: {s} gün.',
    play: 'Oyna',
    playAgain: 'Tekrar oyna',
    streakLine: '🔥 {n} günlük seri',
    notYet: 'henüz çözülmedi',

    calendarTitle: '7 Günlük Hediye',
    dayN: '{n}. gün',
    claim: 'Al',
    claimed: 'Alındı',
    tomorrow: 'Yarın',

    questsTitle: 'Günlük Görevler',
    q_win: '{n} seviye geç',
    q_stars3: '{n} kez 3 yıldız al',
    q_daily: 'Günün seviyesini çöz',
    q_booster: 'Bir güç kullan',
    q_ad: 'Bir ödüllü reklam izle',
    q_play: '{n} kez oyna',
    q_chest: 'Bir yıldız sandığı aç',
    questBonus: 'Üçünü de bitir: bonus ödül',

    wheelTitle: 'Şans Çarkı',
    spinFree: 'Ücretsiz çevir',
    spinAd: 'Reklamla çevir ({n} hak)',
    wheelDone: 'Bugünlük bu kadar, yarın yine gel',
    wheelOdds: 'Olasılıklar',
    wheelWon: 'Kazandın: {r}',

    vipDaily: 'VIP günlük hediyen',
    chestTitle: 'Yıldız Sandığı',
    chestProgress: '{a}/{b} yıldız',
    chestOpen: 'Sandığı aç',
    chestGot: 'Sandıktan çıktı: {r}',
    xpGain: '+{n} Yol puanı',

    roadTitle: 'Altın Yol · Sezon 1',
    roadFree: 'Ücretsiz',
    roadPrem: 'Altın',
    roadUnlock: 'Altın Yol\'u aç',
    roadBody: 'Her kademede daha büyük ödüller, bol güç ve 2 özel görünüm. Oynadıkça ilerlersin; açtığın an geçmiş kademelerin ödülleri de senin.',
    roadOwned: 'Altın Yol açık',
    tier: 'Kademe {n}',
    xpLine: '{a}/{b} puan · sonraki kademe',

    tabOffers: 'Teklifler',
    tabCoins: 'Altın',
    tabBoosters: 'Güçler',
    tabLooks: 'Görünüm',
    coinsPack: '{n} altın',
    bonusTag: '+%{n} bonus',
    popular: 'En popüler',
    bestValue: 'En iyi değer',
    have: 'Sende: {n}',
    buyFor: '{n} altına al',
    boosterOn: '{name} açık',
    boosterBought: '{name} alındı',
    boosterHint: 'Başlamadan önce güç seç',

    starterTitle: 'Başlangıç Paketi',
    specialOffer: 'Sana özel teklif',
    starterBody: '{coins} altın, her güçten {b} tane ve özel görünüm. Yalnızca bir kez sunulur.',
    endsIn: 'Bitişe: {t}',

    vipTitle: 'VIP Kulüp',
    vipPerk1: 'Hiç reklam yok',
    vipPerk2: 'Her gün 100 altın hediye',
    vipPerk3: 'Seviyelerden 2 kat altın',
    vipPerk4: 'Özel VIP görünümü',
    vipWeek: 'Haftalık · {p}',
    vipMonth: 'Aylık · {p}',
    vipActive: 'VIP üyesin. Keyfini çıkar!',
    vipTerms: 'Abonelik, iptal edilmediği sürece dönem sonunda aynı ücretle otomatik yenilenir. Yenilemeden en az 24 saat önce {store} hesap ayarlarından iptal edebilirsin. Ödeme, satın alma onayında hesabından alınır.',
    terms: 'Kullanım koşulları',
    privacy: 'Gizlilik politikası',

    noAdsTitle: 'Reklamsız Paket',
    noAdsBody: 'Bütün reklamlar kalkar, özel görünüm ve 1000 altın hediye.',
    noAdsOwned: 'Reklamsız paket sende. Teşekkürler!',

    skipLevel: 'Seviyeyi atla',
    useBooster: '{name} ile dene',

    rCoins: '{n} altın',
    rBooster: '{n}× {name}',
    rSkin: '{name} görünümü',
    srcStarter: 'Başlangıç paketinde',
    srcVip: 'VIP üyelere özel',
    srcPass: 'Altın Yol · {n}. kademe',
    srcCalendar: '7. gün hediyesi',
    srcPack: 'Reklamsız pakette',

    notifTitle: 'Hatırlatma ister misin?',
    notifBody: 'Günlük hediyen hazır olduğunda ve serin tehlikedeyken akşamları kısa bir hatırlatma gönderelim.',
    yesPlease: 'Evet, hatırlat',
    notNow: 'Şimdi değil',
    nDailyTitle: 'Günlük hediyen hazır',
    nDailyBody: 'Yeni görevler ve şans çarkı seni bekliyor.',
    nStreakTitle: 'Serin tehlikede!',
    nStreakBody: '{n} günlük serini korumak için bugünün seviyesini çöz.',

    sound: 'Ses',
    vibration: 'Titreşim',
    on: 'Açık',
    off: 'Kapalı',
    reset: 'İlerlemeyi sıfırla',
    resetConfirm: 'Bütün seviyeler, altınlar ve görünümler silinecek. Satın alımlar geri yüklenebilir. Emin misin?',
    yes: 'Evet, sıfırla',
    resetDone: 'İlerleme sıfırlandı',
    moneyTitle: 'Bu prototipteki gelir noktaları',
    money1: 'Ödüllü reklam: ipucu, 2 kat altın, şans çarkı, seviye atlama',
    money2: 'Geçiş reklamı: her {n} seviyede bir (VIP ve reklamsız pakette yok)',
    money3: 'Altın paketleri, başlangıç paketi (48 saat), Altın Yol sezon kartı',
    money4: 'VIP abonelik (haftalık / aylık) ve reklamsız paket',
    money5: 'Güçler altınla alınır; altın bitince altın paketi satın alınır',
    menu: 'Menü',
    newBadge: 'Yeni',
    levels: 'Seviyeler',
    lockedLevel: 'Bu seviye henüz kilitli',
    starsTotal: 'Toplam yıldız: {n}',
    language: 'Dil',
    langAuto: 'Otomatik',
  },
  en: {
    level: 'Level {n}',
    daily: 'Daily',
    next: 'Next level',
    retry: 'Retry',
    double: 'Double coins',
    added: 'Added',
    coinsGained: '+{n} coins',
    tries: 'in {n} tries',
    backToLevels: 'Back to levels',
    copyResult: 'Share result',
    copied: 'Copied',
    copyFail: 'Could not copy; select the text and copy it',
    shared: 'Shared',
    close: 'Close',
    start: 'Start',
    equipped: 'Equipped',
    equip: 'Equip',
    needCoins: 'You need {n} more coins',
    buy: 'Buy',
    restore: 'Restore purchases',
    restored: 'Purchases restored',
    purchaseFailed: 'Purchase not completed',
    purchased: 'Purchased!',
    adTitle: 'Ad',
    adBody: 'Prototype simulation. The store version plays a real rewarded ad here.',
    adFailed: 'The ad could not load right now, try again soon',
    interSim: 'The store version shows an interstitial ad here',
    simTitle: 'Test purchase',
    simBody: 'This is a prototype, no real payment is taken. The store version opens the App Store or Google Play payment sheet here.',
    simBuy: 'Simulate purchase',
    simRestore: 'Restore works in the store version',
    cancel: 'Cancel',

    today: 'Today',
    road: 'Golden Road',
    shop: 'Shop',
    settings: 'Settings',

    dailyTitle: "Today's Level",
    dailyNew: 'Everyone plays the same level today. Solve it, earn 50 coins and keep your streak.',
    dailyStreak: 'Streak: {n} days.',
    dailyDone: 'You solved today in {n} tries. Streak: {s} days.',
    play: 'Play',
    playAgain: 'Play again',
    streakLine: '🔥 {n}-day streak',
    notYet: 'not solved yet',

    calendarTitle: '7-Day Gifts',
    dayN: 'Day {n}',
    claim: 'Claim',
    claimed: 'Claimed',
    tomorrow: 'Tomorrow',

    questsTitle: 'Daily Quests',
    q_win: 'Clear {n} levels',
    q_stars3: 'Get 3 stars {n} times',
    q_daily: "Solve today's level",
    q_booster: 'Use a booster',
    q_ad: 'Watch a rewarded ad',
    q_play: 'Play {n} times',
    q_chest: 'Open a star chest',
    questBonus: 'Finish all three: bonus reward',

    wheelTitle: 'Lucky Wheel',
    spinFree: 'Free spin',
    spinAd: 'Spin with an ad ({n} left)',
    wheelDone: "That's it for today, come back tomorrow",
    wheelOdds: 'Odds',
    wheelWon: 'You won: {r}',

    vipDaily: 'Your VIP daily gift',
    chestTitle: 'Star Chest',
    chestProgress: '{a}/{b} stars',
    chestOpen: 'Open chest',
    chestGot: 'From the chest: {r}',
    xpGain: '+{n} Road XP',

    roadTitle: 'Golden Road · Season 1',
    roadFree: 'Free',
    roadPrem: 'Golden',
    roadUnlock: 'Unlock the Golden Road',
    roadBody: 'Bigger rewards at every tier, plenty of boosters and 2 exclusive looks. You progress as you play, and past tiers unlock the moment you buy.',
    roadOwned: 'Golden Road unlocked',
    tier: 'Tier {n}',
    xpLine: '{a}/{b} XP · next tier',

    tabOffers: 'Offers',
    tabCoins: 'Coins',
    tabBoosters: 'Boosters',
    tabLooks: 'Looks',
    coinsPack: '{n} coins',
    bonusTag: '+{n}% bonus',
    popular: 'Most popular',
    bestValue: 'Best value',
    have: 'You have {n}',
    buyFor: 'Buy for {n}',
    boosterOn: '{name} on',
    boosterBought: '{name} bought',
    boosterHint: 'Pick a booster before you start',

    starterTitle: 'Starter Pack',
    specialOffer: 'A special offer for you',
    starterBody: '{coins} coins, {b} of every booster and an exclusive look. Offered only once.',
    endsIn: 'Ends in {t}',

    vipTitle: 'VIP Club',
    vipPerk1: 'No ads at all',
    vipPerk2: '100 free coins every day',
    vipPerk3: 'Double coins from levels',
    vipPerk4: 'Exclusive VIP look',
    vipWeek: 'Weekly · {p}',
    vipMonth: 'Monthly · {p}',
    vipActive: 'You are a VIP. Enjoy!',
    vipTerms: 'The subscription renews automatically at the same price at the end of each period unless cancelled. Cancel at least 24 hours before renewal in your {store} account settings. Payment is charged to your account when you confirm the purchase.',
    terms: 'Terms of use',
    privacy: 'Privacy policy',

    noAdsTitle: 'No-Ads Pack',
    noAdsBody: 'Removes all ads, plus an exclusive look and 1000 bonus coins.',
    noAdsOwned: 'You own the No-Ads Pack. Thank you!',

    skipLevel: 'Skip level',
    useBooster: 'Try with {name}',

    rCoins: '{n} coins',
    rBooster: '{n}× {name}',
    rSkin: '{name} look',
    srcStarter: 'In the Starter Pack',
    srcVip: 'VIP members only',
    srcPass: 'Golden Road · tier {n}',
    srcCalendar: 'Day 7 gift',
    srcPack: 'In the No-Ads Pack',

    notifTitle: 'Want a reminder?',
    notifBody: 'We can send a short evening reminder when your daily gift is ready and when your streak is at risk.',
    yesPlease: 'Yes, remind me',
    notNow: 'Not now',
    nDailyTitle: 'Your daily gift is ready',
    nDailyBody: 'New quests and the lucky wheel are waiting.',
    nStreakTitle: 'Your streak is at risk!',
    nStreakBody: "Solve today's level to keep your {n}-day streak.",

    sound: 'Sound',
    vibration: 'Vibration',
    on: 'On',
    off: 'Off',
    reset: 'Reset progress',
    resetConfirm: 'All levels, coins and looks will be deleted. Purchases can be restored. Are you sure?',
    yes: 'Yes, reset',
    resetDone: 'Progress reset',
    moneyTitle: 'Revenue points in this prototype',
    money1: 'Rewarded ads: hints, double coins, lucky wheel, level skip',
    money2: 'Interstitial ad every {n} levels (none for VIP or No-Ads)',
    money3: 'Coin packs, Starter Pack (48 hours), Golden Road season pass',
    money4: 'VIP subscription (weekly / monthly) and No-Ads Pack',
    money5: 'Boosters cost coins; when coins run out, players buy coin packs',
    menu: 'Menu',
    newBadge: 'New',
    levels: 'Levels',
    lockedLevel: 'This level is still locked',
    starsTotal: 'Total stars: {n}',
    language: 'Language',
    langAuto: 'Automatic',
  },
};
