// Olay Ufku ayarları: metinler (TR/EN), tema, kuyruklu yıldız görünümleri, güçler.
import { createGame } from './game.js';
import { release } from './release.js'; // yayin-ayarlari.json → tools/apply-release.mjs

export const config = {
  id: 'olay-ufku',
  version: release.version,
  createGame,
  dailyLevel: 9,
  shareEmoji: '🌌',
  // Gizlilik ve koşullar adresleri, reklam birimleri ve RevenueCat anahtarları yayin-ayarlari.json dosyasından gelir.
  privacyUrl: release.privacyUrl,
  termsUrl: release.termsUrl || undefined,
  theme: {
    '--bg': '#05060F', '--ink': '#1C1733', '--ink2': '#5A5478',
    '--accent': '#7C5CFF', '--accent-dark': '#5438D9',
    '--pill': 'rgba(255,255,255,.1)', '--pill-ink': '#EEF1FF', '--hud-sub': '#A9B2DA',
    '--panel': '#F6F4FF', '--iap-a': '#140F33', '--iap-b': '#3B2A8C',
  },
  skins: [
    { id: 'buz', name: { tr: 'Buz Kuyruk', en: 'Ice Tail' }, price: 0, a: '#9FE8FF', b: '#3D7BFF' },
    { id: 'gunes', name: { tr: 'Güneş', en: 'Solar' }, price: 120, a: '#FFE08A', b: '#FF7A1A' },
    { id: 'ametist', name: { tr: 'Ametist', en: 'Amethyst' }, price: 150, a: '#E3B8FF', b: '#8E3DFF' },
    { id: 'zumrut', name: { tr: 'Zümrüt', en: 'Emerald' }, price: 200, a: '#B6FFD9', b: '#12B886' },
    { id: 'supernova', name: { tr: 'Süpernova', en: 'Supernova' }, price: 350, a: '#FFD1E8', b: '#FF3D8B' },
    { id: 'kuasar', name: { tr: 'Kuasar', en: 'Quasar' }, starter: true, a: '#FFFFFF', b: '#00E0FF', pulse: true },
    { id: 'kraliyet', name: { tr: 'Kraliyet', en: 'Royal' }, vip: true, a: '#FFE08A', b: '#7C5CFF' },
    { id: 'nebula', name: { tr: 'Nebula', en: 'Nebula' }, pass: 10, a: '#FF9DE2', b: '#5B3DF5' },
    { id: 'pulsar', name: { tr: 'Pulsar', en: 'Pulsar' }, pass: 30, a: '#E8FBFF', b: '#6CF0FF', pulse: true },
    { id: 'hediye', name: { tr: 'Hediye', en: 'Gift' }, calendar: true, a: '#FFB3B3', b: '#2FD39A' },
    { id: 'prizma', name: { tr: 'Prizma', en: 'Prism' }, pack: true, a: '#FFFFFF', b: '#FFFFFF', rainbow: true },
  ],
  // Güçler: altınla alınır, seviye başında seçilir. Mağazada tanesi 120 altın.
  boosters: [
    { id: 'path', icon: 'guide', name: { tr: 'Uzun Rota', en: 'Full Path' }, desc: { tr: 'Nişan alırken kuyruklu yıldızın bütün yolunu kara deliklerin etrafından dolaşarak gösterir.', en: 'While aiming, shows the full path of the comet as it bends around the black holes.' } },
    { id: 'portal', icon: 'target', name: { tr: 'Dev Portal', en: 'Giant Portal' }, desc: { tr: 'Portal 1,6 kat büyür, girmek çok kolaylaşır.', en: 'The portal grows 1.6 times bigger, so it is much easier to reach.' } },
  ],
  ads: {
    // Test reklamı, RST_LIVE_ADS=1 ile derlenmediği sürece açık kalır (bkz. docs/PLAY-STORE-YUKLEME.md).
    testing: typeof __RST_LIVE_ADS__ === 'undefined' || !__RST_LIVE_ADS__,
    interstitialEvery: 4,
    graceMs: 120000,
    units: release.adUnits || undefined, // boşsa Google test birimleri
  },
  iap: { revenuecat: release.revenuecat }, // anahtar yoksa satın alma arayüzü gizlenir
  texts: {
    tr: {
      title: 'Olay Ufku',
      canvasLabel: 'Kuyruklu yıldızı geri çekip bırakarak fırlat',
      shopTitle: 'Kuyruklar',
      welcomeBody: 'Kara delikler ışığı bile büker. Kuyruklu yıldızını geri çek, nişan al ve fırlat: kütleçekimi onu kıvırarak portala taşısın.\n\nOlay ufkuna fazla yaklaşma, yutulursun. Yoldaki yıldız tozlarını toplarsan 3 yıldız alırsın. Altı galaksi, tek tek doğrulanmış 100 bölüm ve sonsuz mod seni bekliyor.',
      tip: 'Geri çek, nişan al, fırlat',
      tipHint: 'İpucu açık: altın rotayı izle',
      sub: '{n} kara delik · portala ulaş',
      rocks: 'asteroitlere dikkat',
      dailySub: 'Bugünün galaksisi, herkes için aynı',
      dust: '{n}/3 yıldız tozu',
      win1: 'Portaldan geçtin!',
      win2: 'Muhteşem rota!',
      win3: 'Kusursuz yörünge!',
      failTitle: 'Olmadı',
      swallowed: 'Olay ufkuna düştün',
      swallowMsg: 'Kara deliğe fazla yaklaştın. Biraz daha uzaktan geç ya da daha hızlı fırlat.',
      crashed: 'Asteroide çarptın',
      crashMsg: 'Açıyı biraz değiştirip asteroidin yanından geç.',
      lost: 'Uzayda kayboldun',
      lostMsg: 'Kütleçekimini kullan: kara deliğin yanından geçerken yolun kıvrılır.',
      near: 'Kıl payı!',
      hint: 'Doğru rotayı göster',
      chLabel: 'Bölüm {n} · {name}',
      ch0: 'Günün Galaksisi', ch1: 'İlk Işık', ch2: 'İkiz Yıldızlar', ch3: 'Asteroit Kuşağı', ch4: 'Beyaz Delikler', ch5: 'Solucan Delikleri', ch6: 'Derin Uzay', ch7: 'Sonsuz Galaksi',
      chIntro1: 'Kara deliğin yanından geç, kütleçekimi yolunu kıvırsın.',
      chIntro2: 'İki kara delik: birinden ötekine sapan gibi fırla.',
      chIntro3: 'Asteroitlere çarpma, aralarından süzül.',
      chIntro4: 'Beyaz delik seni iter. İtişi kullanarak yön değiştir.',
      chIntro5: 'Mor ağızdan giren, turkuaz ağızdan aynı hızla çıkar.',
      chIntro6: 'Hepsi bir arada. Gerçek bir galaksi seni bekliyor.',
      chIntro7: 'Bütün galaksileri geçtin. Şimdi aynalanmış evrenler başlıyor.',
      tipWhite: 'Beyaz delik iter: yanından geçip yön değiştir',
      tipWorm: 'Mor solucan deliğine gir, turkuazdan çık',
      burned: 'Beyaz deliğe çarptın',
      burnMsg: 'Beyaz deliğin çekirdeğine değme; itişi uzaktan kullan.',
    },
    en: {
      title: 'Event Horizon',
      canvasLabel: 'Pull back the comet and release to launch',
      shopTitle: 'Tails',
      welcomeBody: 'Black holes bend even light. Pull back your comet, aim and launch: let gravity curve it into the portal.\n\nDo not get too close to the event horizon, or you will be swallowed. Collect the stardust on the way for 3 stars. Six galaxies, 100 hand-verified levels and an endless mode await.',
      tip: 'Pull back, aim, launch',
      tipHint: 'Hint on: follow the golden route',
      sub: '{n} black hole(s) · reach the portal',
      rocks: 'watch the asteroids',
      dailySub: "Today's galaxy, the same for everyone",
      dust: '{n}/3 stardust',
      win1: 'Through the portal!',
      win2: 'Beautiful route!',
      win3: 'Perfect orbit!',
      failTitle: 'Not quite',
      swallowed: 'Past the event horizon',
      swallowMsg: 'You flew too close to the black hole. Pass farther away or launch faster.',
      crashed: 'Hit an asteroid',
      crashMsg: 'Change the angle a little to slip past the asteroid.',
      lost: 'Lost in deep space',
      lostMsg: 'Use gravity: your path curves as you pass a black hole.',
      near: 'So close!',
      hint: 'Show the right route',
      chLabel: 'Chapter {n} · {name}',
      ch0: 'Galaxy of the Day', ch1: 'First Light', ch2: 'Twin Stars', ch3: 'Asteroid Belt', ch4: 'White Holes', ch5: 'Wormholes', ch6: 'Deep Space', ch7: 'Endless Galaxy',
      chIntro1: 'Pass by the black hole and let gravity curve your path.',
      chIntro2: 'Two black holes: slingshot from one to the other.',
      chIntro3: 'Do not hit the asteroids, slip between them.',
      chIntro4: 'White holes push you away. Use the push to change direction.',
      chIntro5: 'Enter the purple mouth, exit the teal one at the same speed.',
      chIntro6: 'Everything at once. A real galaxy awaits.',
      chIntro7: 'You crossed every galaxy. Mirrored universes begin now.',
      tipWhite: 'White holes push: pass nearby to turn',
      tipWorm: 'Enter the purple wormhole, exit the teal one',
      burned: 'Hit a white hole',
      burnMsg: 'Do not touch the white hole core; use its push from a distance.',
    },
  },
};
