// Kelebek Sarkaç ayarları: metinler (TR/EN), tema, görünümler, reklam ve satın alma kimlikleri.
import { createGame } from './game.js';
import { release } from './release.js'; // yayin-ayarlari.json → tools/apply-release.mjs

export const config = {
  id: 'kelebek-sarkac',
  version: release.version,
  createGame,
  dailyLevel: 9,
  shareEmoji: '🦋',
  // Gizlilik ve koşullar adresleri, reklam birimleri ve RevenueCat anahtarları yayin-ayarlari.json dosyasından gelir.
  privacyUrl: release.privacyUrl,
  termsUrl: release.termsUrl || undefined,
  theme: {
    '--bg': '#D9D2F5', '--ink': '#2B2340', '--ink2': '#5B5270',
    '--accent': '#FF6B5A', '--accent-dark': '#D9483A',
    '--pill': 'rgba(255,255,255,.78)', '--pill-ink': '#2B2340',
  },
  skins: [
    { id: 'mercan', name: { tr: 'Mercan', en: 'Coral' }, price: 0, a: '#FF6B5A', b: '#FFB38A' },
    { id: 'gece', name: { tr: 'Gece', en: 'Midnight' }, price: 120, a: '#3D5AFE', b: '#9FB0FF' },
    { id: 'limon', name: { tr: 'Limon', en: 'Lemon' }, price: 150, a: '#E9B51F', b: '#FFF1A8' },
    { id: 'nane', name: { tr: 'Nane', en: 'Mint' }, price: 200, a: '#27B585', b: '#B8F2DC' },
    { id: 'leylak', name: { tr: 'Leylak', en: 'Lilac' }, price: 250, a: '#8E5BFF', b: '#D6C4FF' },
    { id: 'altin', name: { tr: 'Altın', en: 'Gold' }, price: 600, a: '#C98A12', b: '#FFE08A' },
    { id: 'safak', name: { tr: 'Şafak', en: 'Dawn' }, starter: true, a: '#FF7A45', b: '#FFE3A3' },
    { id: 'kraliyet', name: { tr: 'Kraliyet', en: 'Royal' }, vip: true, a: '#6A3FD4', b: '#F2C94C' },
    { id: 'kuzey', name: { tr: 'Kuzey Işığı', en: 'Aurora' }, pass: 10, a: '#14B8A6', b: '#A0FFB5' },
    { id: 'ay', name: { tr: 'Ay Işığı', en: 'Moonlight' }, pass: 30, a: '#8EA2FF', b: '#FFFFFF' },
    { id: 'hediye', name: { tr: 'Hediye', en: 'Gift' }, calendar: true, a: '#E8505B', b: '#6FCF97' },
    { id: 'gokkusagi', name: { tr: 'Gökkuşağı', en: 'Rainbow' }, pack: true, a: '#FF5FA2', b: '#6FD3FF', rainbow: true },
  ],
  // Güçler: altınla alınır, seviye başında seçilir. Mağazada tanesi 120 altın.
  boosters: [
    { id: 'slow', icon: 'slow', name: { tr: 'Yavaş Çekim', en: 'Slow Motion' }, desc: { tr: 'Sarkaç ve kelebek yarı hızda hareket eder. Doğru anı yakalamak çok kolaylaşır.', en: 'The pendulum and butterfly move at half speed. Timing gets much easier.' } },
    { id: 'wide', icon: 'target', name: { tr: 'Geniş Çiçek', en: 'Big Flower' }, desc: { tr: 'Çiçek neredeyse iki kat büyür, kelebek çok daha kolay konar.', en: 'The flower grows almost twice as big, so landing is much easier.' } },
  ],
  ads: {
    // Test reklamı, RST_LIVE_ADS=1 ile derlenmediği sürece açık kalır (bkz. docs/PLAY-STORE-YUKLEME.md).
    testing: typeof __RST_LIVE_ADS__ === 'undefined' || !__RST_LIVE_ADS__,
    interstitialEvery: 4,
    graceMs: 120000,
    units: release.adUnits || undefined, // boşsa Google test birimleri
  },
  iap: { revenuecat: release.revenuecat }, // anahtar yoksa satın alma arayüzü gizlenir
  texts: {
    tr: {
      title: 'Kelebek Sarkaç',
      canvasLabel: 'Sarkacın ucundaki kelebeği bırakmak için dokun',
      shopTitle: 'Kanatlar',
      welcomeBody: 'Kelebek, çılgınca dönen bir sarkacın ucunda duruyor. Doğru anda dokun, uçsun ve çiçeğe konsun.\n\nSarkaç kaotik: yüzde birkaç saniyelik fark her şeyi değiştirir. Iskalarsan kaç saniye erken ya da geç kaldığını görürsün.',
      tip: 'Bırakmak için dokun',
      tipHint: 'İpucu açık: halka kapanınca dokun',
      now: 'ŞİMDİ',
      subDefault: 'Kelebeği çiçeğe kondur',
      dailySub: 'Bugünün sarkacı, herkes için aynı',
      wind: 'Rüzgâr',
      swaying: 'Çiçek sallanıyor',
      thorn: 'Dikenli dal',
      win1: 'Kondu!',
      win2: 'Güzel iniş!',
      win3: 'Kusursuz!',
      failTitle: 'Iskaladın',
      blocked: 'Dala takıldı',
      early: '{s} saniye erken',
      late: '{s} saniye geç',
      landWould: 'bıraksaydın konacaktı.',
      close: 'Çok yakındı!',
      closeMsg: 'Sarkacın ritmini izle.',
      chaos: 'Kaos acımasız. Sarkacı biraz izle, sonra dene.',
      hint: 'Doğru anı göster',
    },
    en: {
      title: 'Butterfly Pendulum',
      canvasLabel: 'Tap to release the butterfly from the pendulum',
      shopTitle: 'Wings',
      welcomeBody: 'A butterfly rides the tip of a wildly spinning pendulum. Tap at the right moment so it flies off and lands on the flower.\n\nThe pendulum is chaotic: a few hundredths of a second change everything. Miss, and you will see exactly how early or late you were.',
      tip: 'Tap to release',
      tipHint: 'Hint on: tap when the ring closes',
      now: 'NOW',
      subDefault: 'Land the butterfly on the flower',
      dailySub: "Today's pendulum, the same for everyone",
      wind: 'Wind',
      swaying: 'Swaying flower',
      thorn: 'Thorny branch',
      win1: 'Landed!',
      win2: 'Nice landing!',
      win3: 'Perfect!',
      failTitle: 'Missed',
      blocked: 'Caught on a thorn',
      early: '{s} s earlier',
      late: '{s} s later',
      landWould: 'and it would have landed.',
      close: 'So close!',
      closeMsg: 'Watch the rhythm of the pendulum.',
      chaos: 'Chaos is merciless. Watch the pendulum for a moment, then try again.',
      hint: 'Show the right moment',
    },
  },
};
